# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Box / OS
VAGRANT_BOX = 'ubuntu/trusty64'
VM_NAME = 'developer'
VM_USER = 'vagrant'
MAC_USER = 'nikitagurov'
HOST_PATH = '/Users/' + MAC_USER + '/vagrant_envs/' + VM_NAME
GUEST_PATH = '/home/' + VM_USER + '/' + VM_NAME
VM_PORT = 9000
Vagrant.configure(2) do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
    v.gui=true
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo su
    apt-get install -y git
    apt-get install -y maven
    apt-get install -y snapd
    snap install netbeans --classic
    add-apt-repository ppa:openjdk-r/ppa
    apt-get install -y xfce4
    startxfce4&
    apt-get update
    git clone https://github.com/GurovNik/incubator-druid.git
    apt-get install -y openjdk-8-jdk openjdk-8-jre
SHELL
  config.vm.network "forwarded_port", guest: 9090, host: 1234
  config.vm.synced_folder HOST_PATH, GUEST_PATH
  config.vm.synced_folder '.', '/home/'+VM_USER+'', disabled: true
end
