# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Box / OS
VAGRANT_BOX = 'ubuntu/trusty64'
VM_NAME = 'deploy'
VM_USER = 'vagrant'
MAC_USER = 'nikitagurov'
HOST_PATH = '/Users/' + MAC_USER + '/vagrant_envs/' + VM_NAME
GUEST_PATH = '/home/' + VM_USER + '/' + VM_NAME
VM_PORT = 9000
Vagrant.configure(2) do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
    v.gui=true
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo su
    cat idrsa.pub >> /home/vagrant/.ssh/authorized_keys
    add-apt-repository ppa:openjdk-r/ppa
    apt-get update
    apt-get install -y openjdk-8-jdk openjdk-8-jre
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dpkg -i google-chrome-stable_current_amd64.deb

SHELL
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.ssh.insert_key = false
end
